#pragma once

namespace internal
{
    // 
    struct var_script_item_t  {bool readonly; const char* szName; VariableType type; ScopeFlags scope; };

    var_script_item_t std_vars_build_script[] = {
        {false, "TextVar1",                     VariableType::Text,     ScopeFlags::Unknown},   
        {false, "TextVar2",                     VariableType::Text,     ScopeFlags::Unknown},   
        {false, "TextVar3",                     VariableType::Text,     ScopeFlags::Unknown},   
        {false, "TextVar4",                     VariableType::Text,     ScopeFlags::Unknown},   
        {false, "TextVar5",                     VariableType::Text,     ScopeFlags::Unknown},   
        {false, "_argT1",                       VariableType::Text,     ScopeFlags::Unknown},   
        {false, "_argT2",                       VariableType::Text,     ScopeFlags::Unknown},   
        {false, "_argT3",                       VariableType::Text,     ScopeFlags::Unknown},   
        {false, "_argT4",                       VariableType::Text,     ScopeFlags::Unknown},   
        {false, "_argT5",                       VariableType::Text,     ScopeFlags::Unknown},   
        {false, "NumVar1",                      VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "NumVar2",                      VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "NumVar3",                      VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "NumVar4",                      VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "NumVar5",                      VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "_argN1",                       VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "_argN2",                       VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "_argN3",                       VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "_argN4",                       VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "_argN5",                       VariableType::Numeric,  ScopeFlags::Unknown},   
        {false, "BoolVar1",                     VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "BoolVar2",                     VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "BoolVar3",                     VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "BoolVar4",                     VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "BoolVar5",                     VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "_argB1",                       VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "_argB2",                       VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "_argB3",                       VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "_argB4",                       VariableType::Bool,     ScopeFlags::Unknown},   
        {false, "_argB5",                       VariableType::Bool,     ScopeFlags::Unknown},   
      //{false, "Timestamp1",                   VariableType::_TS,      ScopeFlags::Unknown},
      //{false, "Timestamp2",                   VariableType::_TS,      ScopeFlags::Unknown},
      //{false, "Timestamp3",                   VariableType::_TS,      ScopeFlags::Unknown},
      //{false, "Timestamp4",                   VariableType::_TS,      ScopeFlags::Unknown},
      //{false, "Timestamp5",                   VariableType::_TS,      ScopeFlags::Unknown},
        {true,  "CameraSerialNum",              VariableType::Text,     ScopeFlags::CameraSetting},
        {true,  "CameraName",                   VariableType::Text,     ScopeFlags::CameraSetting},  
        {true,  "CurUserName",                  VariableType::Text,     ScopeFlags::UserSetting},     
        {true,  "CurSensorTemp",                VariableType::Numeric,  ScopeFlags::CameraSetting},   
        {true,  "CurImgSetupName",              VariableType::Text,     ScopeFlags::CameraSetting},   
        {true,  "ImgUserName",                  VariableType::Text,     ScopeFlags::ImageMetaData},   
        {true,  "ImgTitle",                     VariableType::Text,     ScopeFlags::ImageMetaData|ScopeFlags::FilePath},
        {true,  "ImgMemo",                      VariableType::Text,     ScopeFlags::ImageMetaData},
        {true,  "DBRecID",                      VariableType::Integer,  ScopeFlags::ImageMetaData},
        {true,  "ImgSeqLen",                    VariableType::Integer,  ScopeFlags::ImageMetaData},
        {true,  "ImgSeqIdx",                    VariableType::Integer,  ScopeFlags::ImageMetaData},
        {true,  "ImgElapsedTime",               VariableType::Text,     ScopeFlags::ImageMetaData},
        {true,  "ImgSetupName",                 VariableType::Text,     ScopeFlags::ImageMetaData},
        {true,  "ImgSensorTemp",                VariableType::Numeric,  ScopeFlags::ImageMetaData},
        {true,  "MacroLoopNum",                 VariableType::Integer,  ScopeFlags::Unknown},
        {true,  "MacroCmdCanceled",             VariableType::Bool,     ScopeFlags::Unknown},
        {true,  "MacroCmdFailed",               VariableType::Bool,     ScopeFlags::Unknown},
      //{true,  "ImgDate",                      VariableType::_DATE ,   ScopeFlags::Unknown},
      //{true,  "ImgTime",                      VariableType::_TIME ,   ScopeFlags::Unknown},
      //{true,  "RptDate",                      VariableType::_DATE ,   ScopeFlags::Unknown},
      //{true,  "RptTime",                      VariableType::_TIME ,   ScopeFlags::Unknown},
      //{true,  "ImgTimestamp",                 VariableType::_TS,      ScopeFlags::Unknown|ScopeFlags::ImageMetaData},
        {true,  "RptPageNum",                   VariableType::Integer,  ScopeFlags::Reporting}, 
        {true,  "RptPageCount",                 VariableType::Integer,  ScopeFlags::Reporting},
        {true,  "RptRecNum",                    VariableType::Integer,  ScopeFlags::Reporting}, 
        {true,  "RptRecCount",                  VariableType::Integer,  ScopeFlags::Reporting},
        {true,  "RunTimeText",                  VariableType::Text,     ScopeFlags::Reporting},
        {true,  "MinExposure",                  VariableType::Numeric,  ScopeFlags::CameraSetting},
        {true,  "MaxExposure",                  VariableType::Numeric,  ScopeFlags::CameraSetting},
        {true,  "LiveImgOpen",                  VariableType::Bool,     ScopeFlags::ApplicationState},
        {true,  "LiveImgRunning",               VariableType::Bool,     ScopeFlags::ApplicationState},
        {true,  "LiveImgCount",                 VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "LiveImgContrast",              VariableType::Numeric,  ScopeFlags::ImageMetaData},
        {true,  "OperationMode",                VariableType::Text,     ScopeFlags::ApplicationState},
        {true,  "ImgMeasWidth",                 VariableType::Numeric,  ScopeFlags::Measurment|ScopeFlags::ApplicationState},
        {true,  "ImgMeasLength",                VariableType::Numeric,  ScopeFlags::Measurment|ScopeFlags::ApplicationState},
        {true,  "ImgMeasArea",                  VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "ImgMeasPerimeter",             VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "ImgMeasAngle",                 VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "ImgMeasRadius",                VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "ImgMeasDiameter",              VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "ImgMeasCircumference",         VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "ImgMeasMajorAxis",             VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "ImgMeasMinorAxis",             VariableType::Numeric,  ScopeFlags::ImageMetaData|ScopeFlags::Measurment},
        {true,  "PICSLinkDataTransferDir",      VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
      //{true,  "TwainMode",                    VariableType::Bool,     ScopeFlags::ApplicationState},
        {true,  "NumDocWindows",                VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "NumImgDocWindows",             VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "NumImgSeqDocWindows",          VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "NumThumbnailDocWindows",       VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "NumRptTemplateDocWindows",     VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "NumDlgDesignDocWindows",       VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "DocWindowType",                VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "DocWindowMode",                VariableType::Integer,  ScopeFlags::ApplicationState},
        {true,  "DocNewOrModified",             VariableType::Bool,     ScopeFlags::ApplicationState},
        {true,  "PrefsFilePath",                VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "UserDesktopPath",              VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "CommonDesktopPath",            VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "OpenImgFilePath",              VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "SaveImgFilePath",              VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "OpenImgSeqFilePath",           VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "SaveImgSeqFilePath",           VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "OpenRptFilePath",              VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "SaveRptFilePath",              VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "MacroFilePath",                VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "MovieExportFilePath",          VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "BaseMacroFilePath",            VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "BaseDialogFilePath",           VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "BaseRptFilePath",              VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "BaseObjImgFilePath",           VariableType::Text,     ScopeFlags::ApplicationState|ScopeFlags::FilePath},
        {true,  "AppVisible",                   VariableType::Bool,     ScopeFlags::ApplicationState},
        {true,  "AppActive",                    VariableType::Bool,     ScopeFlags::ApplicationState},
        {false, "CalMarkOrientation",           VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "CalMarkColor",                 VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "CalMarkLineThickness",         VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "CalMarkLineEndLength",         VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "CalMarkShowText",              VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "CalMarkTextFontName",          VariableType::Text,     ScopeFlags::UserSetting},
        {false, "CalMarkTextFontSize",          VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "CalMarkTextRotation",          VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "CalMarkDecimals",              VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MeasurementColor",             VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MeasurementLineThickness",     VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MeasurementTextFontName",      VariableType::Text,     ScopeFlags::UserSetting},
        {false, "MeasurementTextFontSize",      VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MeasurementTextRotation",      VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MeasurementDecimals",          VariableType::Integer,  ScopeFlags::UserSetting},
        {false, "MeasurementShowCircleArea",    VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowCircleRadius",  VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowCircleDiameter",VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowCircleCircum",  VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowRectArea",      VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowRectLength",    VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowRectWidth",     VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowRectPerim",     VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowEllipseArea",   VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowEllipseMajAxis",VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowEllipseMinAxis",VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowEllipsePerim",  VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowRegionArea",    VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "MeasurementShowRegionPerim",   VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "AnnotLineBorderThickness",     VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "AnnotTextLineColor",           VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "AnnotBkgdFillColor",           VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "AnnotTextFontName",            VariableType::Text,     ScopeFlags::UserSetting},
        {false, "AnnotTextFontSize",            VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "AnnotTextRotation",            VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "AnnotTextJustification",       VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "AnnotTextBackgroundMode",      VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "AnnotFillObject",              VariableType::Bool,     ScopeFlags::UserSetting},
        {false, "AnnotArrowHeadSize",           VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MagnifierWindowWidth",         VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MagnifierWindowHeight",        VariableType::Numeric,  ScopeFlags::UserSetting},
        {false, "MagnifierMagnificationFactor", VariableType::Numeric,  ScopeFlags::UserSetting}
    };

} // end namespace internal